### ISSUE TITLE
rbenv configuration problem in 2.4.3

### ISSUE THREAD

**Issue by jmarrec** [NREL/docker-openstudio#11]
I just pulled docker 2.4.3, and I cannot run the following command:

      ~/.rbenv/shims/ruby -I /usr/Ruby/openstudio.so model_tests.rb $test_filter

This used to work in all docker containers back to 2.0.5.

I see that ruby is now installed from the openstudio-server script:  https://github.com/NREL/docker-openstudio/commit/17e4e72377ce2d6239ec2f0d2494691013891858

It used to be based on rbenv, as highlighted in the docker hub **now-outdated** Dockerfile: https://hub.docker.com/r/nrel/openstudio/~/dockerfile/

Two things:
* Should I expect to just have the right system ruby in the docker containers going forward?
* Please update the dockerhub dockerfile.

**Comment by nllong** [comment]
The command will now be

`ruby model_tests.rb $test_filter`

You don't need to fully qualify the path to ruby nor pass in the openstudio.so model. If we absolutely need to support an absolute path to ruby in the rbenv shims dir, then we can create a symlink, but I'd rather not do that.

**Comment by jmarrec** [comment]
That's what I already replaced it with (I saw that it was configured so that the include switch isn't need) I just wanted to know if I should expect variations going forward. Seems like I shouldn't.

I'll close now, but it'd be nice if the docker hub dockerfile could be updated to match latest, thanks!

**Comment by nllong** [comment]
I hope there aren't any future variations (famous last words?).

Are you referring to this [dockerhub file](https://hub.docker.com/r/nrel/openstudio/~/dockerfile/)? I have no idea where docker hub is getting that file. I would think it would pull from the master version from [github](https://github.com/NREL/docker-openstudio/blob/master/Dockerfile).

**Comment by jmarrec** [comment]
yes I'm referring this file (weird, clicking on your link doesn't work, though if I navigate to it myself, I get the same one...)
