### ISSUE TITLE
add image based on ubuntu 22.04

### ISSUE THREAD

**Issue by wenyikuang** [NREL/docker-openstudio#171]
For consistance of openstudio-server, release a version of docker-image based on new LTS ubuntu.

**Comment by brianlball** [comment]
getting ruby 2.7.2 on 22.04 can be a challenge.  
not sure if this is the best way but heres an example
https://github.com/NREL/docker-openstudio-r/blob/JammyJellyfish/Dockerfile#L85

**Comment by wenyikuang** [comment]
> getting ruby 2.7.2 on 22.04 can be a challenge. not sure if this is the best way but heres an example https://github.com/NREL/docker-openstudio-r/blob/JammyJellyfish/Dockerfile#L85

Really helpful!

It's WIP in https://github.com/NREL/docker-openstudio/tree/2204Base now.

**Comment by wenyikuang** [comment]
https://hub.docker.com/layers/nrel/openstudio/3.7.0-2204/images/sha256-6a064196d246b87a69e298ba9c56a9bf0179ad0105ec6e81ff52047df09d17ab

Done.

Next time if you need update the 2204 series image, you could just merge PR into 2204-release branch. (based on previous change)

Close the issue.
