### ISSUE TITLE
Use ubuntu:18.04 as base image

### ISSUE THREAD

**Issue by nmerket** [NREL/docker-openstudio#32]
Is there any reason we can't use `ubuntu:18.04` as the base image for this? I want to build a derivative image from it and install python 3.6. With the current image I have to build python myself since it's not in the repository for these older versions of ubuntu.

**Comment by nllong** [comment]
We will move over to 18.04 once OpenStudio supports it.

**Comment by anyaelena** [comment]
working on this for OS 3
