### ISSUE TITLE
Remove sudo from install_ruby.sh script

### ISSUE THREAD

**Issue by edward-ellis** [NREL/docker-openstudio#35]
I am using continuous integration to run tests on our proprietary Open Studio code.  I have chosen to use your docker-openstudio container, but have needed to make a few small changes and then build our own custom image.  This was working fine until we upgraded from version 1.14 to version 2.6.
 
Our continuous integration build host is considered critical infrastructure and is therefore locked down very tightly.  All attempts to download from the Internet are filtered through a proxy.  The build host pushes the proxy configuration down into the Docker environment and all goes well until you download and run https://raw.githubusercontent.com/NREL/OpenStudio-server/develop/docker/deployment/scripts/install_ruby.sh.
 
This script does sudo even though all Docker builds run as root.  The sudo drops all the environment variables because that’s what sudo is supposed to do, but that destroys the entire proxy configuration and all the downloads fail.  Since this script is being used in the Docker build and is already running as root, could you see your way clear to use a version with no commands as sudo or perhaps test whether you’re running as root already?

**Comment by nllong** [comment]
The above change should address the problem. Make sure to call `sudo install_ruby.sh <args>` if you are not root.

I will merge the changes into develop on OpenStudio-server once all the tests pass at which point the docker builds will use the new script.

**Comment by nllong** [comment]
The required script has been merged down. Let me know if this does not fix your issue.
