### ISSUE TITLE
Run OS locally

### ISSUE THREAD

**Issue by Mo11068** [NREL/docker-openstudio#36]
Hi,

I am trying to run OS (PAT) on a local machine. I pulled the OS 2.6.0 using the following command:
docker pull nrel/openstudio:2.6.0
When  that is complete, I tried to run it: 
docker run -it --rm nrel/openstudio:2.6.0 /bin/bash 
but after hitting the enter key, it shows the following root
root@65aa977e6d10:/var/simdata/openstudio#
which stops me!. Could you please help me with that?

**Comment by nllong** [comment]
The main use case for the OpenStudio docker containers are to run OpenStudio/EnergyPlus simulations non-interactively and without the GUI application. Another ticket was opened ago around running the GUI applications from within the containers using X11 (https://github.com/NREL/docker-openstudio/issues/1).
