### ISSUE TITLE
Run docker-openstudio in the local

### ISSUE THREAD

**Issue by yunyangye922** [NREL/docker-openstudio#4]
I create docker and pull docker-openstudio (docker pull phylroy/docker-openstudio). However, I have no idea how to run the gui in my local computer. Is there instruction to do the work?

**Comment by edward-ellis** [comment]
phylroy has submitted a pull request to make it possible to run the GUI.  However, he expects you to have installed an X-Windows server on your local computer.  In the pull request he suggests Xming Server, which is Windows native and Open Source.  You'll need to figure out the details of using X-Windows on your local computer and any Docker specific networking issues.

**Comment by nllong** [comment]
If we are going to support running the GUI from these containers, then one should create a new container (e.g. docker-openstudio-gui) dependent on this container and document functionality there. This container is designed to run ruby scripts and openstudio CLI.
