### ISSUE TITLE
Ruby update

### ISSUE THREAD

**Issue by anyaelena** [NREL/docker-openstudio#47]
Gems are dropping 2.2 support right and left.

**Comment by nllong** [comment]
my understanding is that OpenStudio is going to upgrade to ruby 2.x (where
x is >= 4) soon. We need to get that timeline as soon as possible.

**Comment by macumber** [comment]
Openstudio 3 will use ruby 2.5.1, initial test installers in March and official release in September

**Comment by anyaelena** [comment]
This is bundled into issue #56 - update for OS 3.
