### ISSUE TITLE
Missing packages to be able to run OpenStudioApp from the image

### ISSUE THREAD

**Issue by pachi** [NREL/docker-openstudio#5]
Some packages are missing to be able to run the OpenStudioApp from the image:
 libnss3 libXcursor1 libxcomposite1 libasound2 libxtst6

There's also a related bug https://github.com/NREL/OpenStudio/issues/2874 which prevents the app to start but that can be papered over running the app from /usr/bin/OpenStudioApp and adding this to the Dockerfile (so the minimal startup resources can be found):

RUN mkdir -p /usr/share/openstudio-$OPENSTUDIO_VERSION/
RUN cp -r /usr/Resources/* /usr/share/openstudio-$OPENSTUDIO_VERSION/

**Comment by nllong** [comment]
These containers were not designed to run the OpenStudioApp. These containers are more for running openstudio scripts or the openstudio CLI

**Comment by pachi** [comment]
I understand that, but given that the app only works in an old Ubuntu version (14.04LTS), using the docker image was really convenient. Also, it's very useful for debugging problems with measures, where you can apply them from the GUI.

**Comment by nllong** [comment]
I think we should make another container that has GUI capabilities.
“OpenStudio-GUI”?
