### ISSUE TITLE
Add branch for develop3

### ISSUE THREAD

**Issue by macumber** [NREL/docker-openstudio#56]
@

**Comment by anyaelena** [comment]
@macumber @tijcolem is there an openstudio build for me to work with here?

**Comment by anyaelena** [comment]
@macumber @tijcolem @nllong @brianlball I'm assuming the following two major updates + all related dependencies. Let me know if I'm missing something.

1) Update base image to ubuntu:18.04.  This base image uses Minimal Ubuntu and is 15M smaller than 16.04 which is nice. 
1) Update to Ruby 2.5.1

**Comment by tijcolem** [comment]
@anyaelena no dev3 builds yet.  sorting out a few conan reltated issues but should get something out soon.

**Comment by anyaelena** [comment]
@tijcolem my misunderstanding.  i'll stay tuned.

**Comment by anyaelena** [comment]
image has been published for as openstudio:develop3.  I removed a bunch of package installs; we may want to add some (like `sudo`) back in for convenience.  

I'm surprised that this image isn't smaller.  it's ~30MB smaller than the 2x images.
