### ISSUE TITLE
Update ruby to use 2.5.5 instead of 2.5.1, like OpenStudio does

### ISSUE THREAD

**Issue by jmarrec** [NREL/docker-openstudio#97]
Dockerfile uses ruby 2.5.1

https://github.com/NREL/docker-openstudio/blob/48f95764b6249d9f6ea87957c7d6e2e95e3dfe11/Dockerfile#L20

While OpenStudio uses ruby 2.5.5

https://github.com/NREL/OpenStudio/blob/97129fb8b62bfa8427ab8a792a904a5a5ce916ce/ConanInstall.cmake#L62

**Comment by tijcolem** [comment]
Right. This is b/c we are using the system ruby that is shipped with Ubuntu 18.04 and is the official .deb package when you install via apt and is compatible with 2.5.5. That said we can certainly install 2.5.5.

**Comment by brianlball** [comment]
we now use ruby 2.7.2 like OS
https://github.com/NREL/docker-openstudio/blob/develop/Dockerfile#L44

**Comment by jmarrec** [comment]
House cleaning for the win! Thanks @brianlball :)
